dbt_demo:
  target: dev
  outputs:
    dev:
      type: duckdb
      # Use absolute path so DbtProjectComponent's copy uses the same DB
      path: "{{ env_var('DBT_DUCKDB_PATH', 'dev.duckdb') }}"
      threads: 4